'''Run pharmit on specified database with query'''
# File originally created by Rishal Aggarwal (Koes Lab) to calculate the F1Score. 
# File last modified by Sumeet Kothare on 18Aug2025.
# Input: 
# The .json query file (with pharmacophore features) 
# The Pharmit database directory or link to search
# Active Molecules SMILES (Simplified Molecular Input Line Entry System) file
# Decoy Molecules SMILES

"""
CalcF1Score.py

Objectives: Considers a pharmacophore (set of molecular features) from a given JSON file to search a provided pharmit database for molecules matching the pharmacophore in the JSON file. The list of active and decoys allows for calculating the recall, precision, and F1 scores.

Inputs:
1. JSON file containing the pharmacophore
2. Directory for the pharmit database
3. List of active molecules
4. List of decoy molecules

Output:
1. Metrics (F1 Score, Enrichment Factor, Recall, Precision, and Hit Rate) for the molecules matched corresponding to the provided pharmacophore (set of molecular features).

"""
"""
Example Command to run:
cd ~/PhinderSK/phinder

python3 CalcF1Score.py Top3.json \
  /net/galaxy/home/koes/rishal/covid_moonshot/covid_moonshot \
  --actives /net/galaxy/home/koes/rishal/covid_moonshot/actives_smiles.ism \
  --decoys  /net/galaxy/home/koes/rishal/covid_moonshot/decoys_smiles.ism

"""

import argparse, subprocess

parser = argparse.ArgumentParser(description='Run pharmit on specified database with query and report F1 score')
# Path to pharmacophore JSON file (for example, one generated by Phinder.py)
parser.add_argument("query",help="Query file (json) to search with")
# Path to the pharmit database to search from
parser.add_argument("db",help="Pharmit database to search")
# Path to SMILES file of actives (this script only counts how many SMILES of active molecules exist.)
parser.add_argument("--actives",default="actives_final.ism",help="Name of actives smiles file",required=False)
# Path to SMILES of decoys (this script only counts how many SMILES of decoy molecules exist.)
parser.add_argument("--decoys",default="decoys_final.ism",help="Name of decoys smiles file",required=False)
args = parser.parse_args()
print(args.db, args.query)

try:
    num_decoys = len(open(args.decoys).readlines()) # count lines
    num_actives = len(open(args.actives).readlines()) # count lines
    num_total = num_decoys + num_actives # total molecules in the database; each line is typically one molecule.
    # Updated command with full paths
    print(f"There are {num_actives} active molecules and {num_decoys} decoy molecules for a total of {num_total}.")
    '''
    Hard-coded database example to run Pharmit as a subprocess:

    pharmit_cmd = f'/path/to/pharmit dbsearch -dbdir /net/galaxy/home/koes/rishal/covid_moonshot/covid_moonshot -in {args.query} -extra-info -max-orient=1 -reduceconfs=1'
    
    output = subprocess.check_output(pharmit_cmd, shell=True)
    output = output.decode()
    lines = output.split('\n')
    '''

    '''
    Run Pharmit as a subprocess:
    
    1. pharmit dbsearch: searches a database of conformers with a pharmacophore query

    2. -dbdir {args.db}: directory of the Pharmit database to search (Moonshot, Fresco etc.)

    3. -in {args.query}: JSON query (Top10 features or so from the Phinder output)

    4. -extra-info: print more columns per hit (index, rmsd, size, rotbonds, name, etc.)

    5. -max-orient=1: limit the orientations per molecule to keep the runtime small

    6. -reduceconfs=1: This is critical as it limits the number of conformers per molecule to 1 so that each molecule appears at most once in the output and avoid double-counting the same actives multiple times.
    '''
    output = subprocess.check_output(f'pharmit dbsearch -dbdir {args.db} -in {args.query} -extra-info -max-orient=1 -reduceconfs=1',shell=True) # returns STDOUT text as bytes.
    output = output.decode() # convert the bytes to strings
    lines = output.split('\n') # split into lines. Each hit is printed to one line.

    # Initialize counters:
    hits = 0 # Total numnber of matched molecules returned by Pharmit
    tp = 0 # true positives (matched molecules that are actives)
    for line in lines: # Iterature through every hit
        vals = line.split(',') #index,rmsd, molweight, #rotbonds,name, internal stuff
        if len(vals) != 7:
            continue #skip other rows
        hits += 1
        name = vals[4] # Field 5 contains the molecule name
        if 'active' in name:
            tp += 1
            
    recall = tp/num_actives
    if recall == 0: #avoid divide by zero
        precision = 0
        f1 = 0
    else:
        precision = tp/hits
        f1 = 2*(precision*recall)/(precision+recall)
    enrichment_factor = precision/(num_actives/num_total) # EF > 1 means actives were found better than just random chance.
    hit_rate = hits/num_total

    print(f'F1: {f1:5f} Recall: {recall:5f} Precision: {precision:5f} Hit rate: {hit_rate:5f} Enrichment Factor: {enrichment_factor:5f}')
except Exception as e:
    print(f"An error occurred: {str(e)}")
    import traceback
    traceback.print_exc()